markdown: rdiscount
pygments: true
permalink: posts/:title
paginate: 6
paginate_path: "posts/page:num"
rdiscount:
  extensions: [smart]
nav:
  - text: photography
    url: /photography/index.html
  - text: posts
    url: /posts/index.html
  - text: about
    url:  /about/index.html

name: rpk
url: 127.0.0.1:4000/
description: A fantastic blog that is fantastic.
twitter: rpk0_
github: rpk0
flickr: rp0
gravatar_url: https://s.gravatar.com/avatar/8bc43bee9040db6434f0842501858358?s=80

